- name: PROVISION VPC SUBNETS & F5 INSTANCES
  hosts: localhost
  connection: local
  gather_facts: no


  vars_files:
    - ../creds/big_creds.yaml

  vars:

    uri_method: POST

  tasks:

    - name: Issue AS3 declaration
      uri:
        url: https://3.9.55.150/mgmt/shared/appsvcs/declare
        #url: https://10.1.1.245/mgmt/shared/appsvcs/declare
        method: "{{uri_method}}"
        user: "{{bigip_user}}"
        password: "{{bigip_pass}}"
        body: "{{ lookup('file','./as3-declarations/simple-as3.json') }}"
        force_basic_auth: yes
        body_format: json
        validate_certs: no
        status_code: 200